language: node_js
sudo: false
branches:
  only:
    - gh-pages # test gh-pages
    - /(.*)/   # test all branches
before_script:
  - npm install -g ndgeojson-lint
  - npm install -g jsonlint
script:
  - jsonlint -q name_index.json
  - find geojson -name '*.geojson' -exec cat {} \; | jq -c . | ndgeojson-lint
